### ISSUE TITLE
Functional timeout errors with core/text

### ISSUE THREAD

**Issue by kitsonk** [dojo/core#159]
We get this [fairly regularly now](https://travis-ci.org/dojo/core/builds/129459541#L287):

Testing locally doesn't seem to cause a problem.  5 seconds does seem like a long time, so I am not sure why these are not completing (and why it seems to only be fairly recently that they started to fail).  Happens in Firefox, Android and sometimes in IE10 or IE11... 😭 

```
× firefox on Windows 10 - unit tests - request_browser - .get (5.017s)
CancelError: Timeout reached on firefox on Windows 10 - unit tests - request_browser - .get
  at Test.prototype.restartTimeout/this._timer<  <__intern/lib/Test.js:132:20>
× firefox on Windows 10 - unit tests - request_browser - JSON responseType filter (5.01s)
CancelError: Timeout reached on firefox on Windows 10 - unit tests - request_browser - JSON responseType filter
  at Test.prototype.restartTimeout/this._timer<  <__intern/lib/Test.js:132:20>
× firefox on Windows 10 - text plugin - correct text (5.007s)
CancelError: Timeout reached on firefox on Windows 10 - text plugin - correct text
  at null._onTimeout  <node_modules/intern/lib/Test.js:132:20>
  at Timer.listOnTimeout  <timers.js:119:15>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Command  <node_modules/intern/node_modules/leadfoot/Command.js:566:15>
  at <node_modules/intern/lib/Test.js:206:37>
  at Promise.cancel  <node_modules/intern/browser_modules/dojo/Promise.ts:343:37>
  at null._onTimeout  <node_modules/intern/lib/Test.js:134:21>
  at Timer.listOnTimeout  <timers.js:119:15>
```

**Comment by kitsonk** [comment]
Setting the concurrency is = 1 didn't clear up the issues...

**Comment by kitsonk** [comment]
These were fixed.
